package webhub

import "strings"

// Rule-table types for the generated site rules (internal/webhub/sites.go).
//
// ⚠️ sites.go is GENERATED by tools/gen-webhub-sites.go from the upstream
// universal-web-api config/sites.json. These types are hand-written because
// they define the Go-side semantics the generated data must fit, but the DATA
// itself must never be edited by hand.

// SiteRule is one supported site: its domain, the default preset, and every
// preset the site declares.
type SiteRule struct {
	// Domain is the normalized lowercase hostname (e.g. "chat.deepseek.com").
	// It is both the tab-matching key and the base of the model-id space.
	Domain string
	// DefaultPreset names the preset used when a caller does not pin one.
	DefaultPreset string
	// Presets is the site's preset list, sorted by name (stable for the UI).
	Presets []Preset
}

// Preset is one named interaction recipe for a site (a model variant, a
// "temporary chat" mode, an image mode, …).
type Preset struct {
	// Name is the upstream preset label. It appears verbatim in the
	// `<domain>/<preset>` model id, so it may contain spaces and non-ASCII
	// characters — treat it as an opaque path segment.
	Name string
	// Selectors maps the logical selector key (input_box, send_btn,
	// result_container, new_chat_btn, …) to a CSS selector. Empty/absent keys
	// are simply missing from the map.
	Selectors map[string]string
	// Stream configures how the reply is watched.
	Stream StreamConfig
	// Workflow is the flattened declarative step list. GROUP steps are
	// inlined by the generator, so the interpreter runs a single flat loop.
	Workflow []Step
}

// Step is one declarative workflow action.
type Step struct {
	// Action is the upper-cased upstream action name (CLICK, FILL_INPUT,
	// KEY_PRESS, STREAM_WAIT, WAIT, JS_EXEC, CAPTURE, IF, SELECT_MODEL, …).
	Action string
	// Target is the selector key (input_box) or the raw CSS/JS payload the
	// upstream step names.
	Target string
	// Optional marks a best-effort step: failure is logged, never fatal, and
	// it runs under a bounded timeout (see optionalStepTimeout) so a stale
	// selector cannot consume the whole request budget (P0 defect ③).
	Optional bool
	// Seconds carries the numeric payload of a WAIT step (upstream
	// workflow[].value = N seconds). 0 for every other action.
	Seconds float64
	// Label is the human-readable upstream step label (diagnostics only).
	Label string
}

// StreamConfig describes how a reply is observed.
type StreamConfig struct {
	// Mode is the upstream stream_config.mode: "network" (CDP interception)
	// or "dom" (poll the result container). DOM is the universal fallback and
	// the only mode P0 validated end-to-end on a real site, so the driver
	// always falls back to it.
	Mode string
	// HardTimeoutSec is the overall reply budget (upstream hard_timeout).
	// 0 = use the driver default.
	HardTimeoutSec float64
	// ListenPattern is the URL substring/pattern the network mode subscribes
	// to (upstream network.listen_pattern). Empty = network mode unusable.
	ListenPattern string
	// Parser names the upstream SSE parser for this site (e.g. "deepseek").
	Parser string
}

// Selector keys used by the workflow interpreter. They are the upstream
// selector_definitions keys that this port actually consumes.
const (
	SelInputBox      = "input_box"
	SelSendButton    = "send_btn"
	SelResultContain = "result_container"
	SelNewChat       = "new_chat_btn"
	SelStopButton    = "stop_btn"
	SelGenerating    = "generating_indicator"
)

// action names recognized by the interpreter (upstream action set, upper-cased
// by the generator).
const (
	ActionClick      = "CLICK"
	ActionFillInput  = "FILL_INPUT"
	ActionKeyPress   = "KEY_PRESS"
	ActionStreamWait = "STREAM_WAIT"
	ActionWait       = "WAIT"
	ActionCapture    = "CAPTURE"
	ActionJSEval     = "JS_EXEC"
	ActionSelect     = "SELECT_MODEL"
	ActionIf         = "IF"
	ActionReadonly   = "READONLY_HINT"
	ActionCoordClick = "COORD_CLICK"
)

// SiteRuleByDomain returns the rule for a domain, or nil when the site is not
// supported.
func SiteRuleByDomain(domain string) *SiteRule {
	target := normalizeDomain(domain)
	if target == "" {
		return nil
	}
	for i := range siteRules {
		if siteRules[i].Domain == target {
			return &siteRules[i]
		}
	}
	return nil
}

// AllSites returns every supported site rule (a slice over the generated
// table; the table itself is immutable after init).
func AllSites() []SiteRule {
	out := make([]SiteRule, len(siteRules))
	copy(out, siteRules)
	return out
}

// SiteDomains returns the sorted domain list of every supported site.
func SiteDomains() []string {
	out := make([]string, 0, len(siteRules))
	for i := range siteRules {
		out = append(out, siteRules[i].Domain)
	}
	return out
}

// PresetByName returns the named preset of a site rule, or nil.
func (r *SiteRule) PresetByName(name string) *Preset {
	if r == nil {
		return nil
	}
	if name != "" {
		for i := range r.Presets {
			if r.Presets[i].Name == name {
				return &r.Presets[i]
			}
		}
		return nil
	}
	return r.Default()
}

// Default returns the site's default preset: the one named by DefaultPreset,
// else the first declared preset. nil only when the site declares none.
func (r *SiteRule) Default() *Preset {
	if r == nil {
		return nil
	}
	if r.DefaultPreset != "" {
		for i := range r.Presets {
			if r.Presets[i].Name == r.DefaultPreset {
				return &r.Presets[i]
			}
		}
	}
	if len(r.Presets) > 0 {
		return &r.Presets[0]
	}
	return nil
}

// PresetNames returns the site's preset names in declaration order.
func (r *SiteRule) PresetNames() []string {
	if r == nil {
		return nil
	}
	out := make([]string, 0, len(r.Presets))
	for i := range r.Presets {
		out = append(out, r.Presets[i].Name)
	}
	return out
}

// Selector resolves a logical selector key for a preset, returning "" when the
// site does not declare it.
func (p *Preset) Selector(key string) string {
	if p == nil {
		return ""
	}
	return strings.TrimSpace(p.Selectors[key])
}

// HasSelectors reports whether the preset declares the minimum selector set a
// send-and-read turn needs (input box + result container). Sites missing them
// cannot be driven and are reported as such by the UI instead of failing
// obscurely mid-request.
func (p *Preset) HasSelectors() bool {
	return p.Selector(SelInputBox) != "" && p.Selector(SelResultContain) != ""
}
